# Generated by Django 3.2.8 on 2021-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Время вылета')),
                ('departure_airport', models.CharField(blank=True, max_length=4, null=True, verbose_name='Аэропорт вылета')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прилета')),
                ('arrival_airport', models.CharField(blank=True, max_length=4, null=True, verbose_name='Аэропорт прилета')),
            ],
            options={
                'ordering': ('-departure_time',),
                'unique_together': {('departure_time', 'departure_airport', 'arrival_time', 'arrival_airport')},
            },
        ),
    ]
